# JuliaFormatter configuration for OpenEng.jl
# For options, see: https://domluna.github.io/JuliaFormatter.jl/stable/config/

# Indentation
indent = 4
margin = 92

# Style
style = "blue"

# Formatting options
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_use_return = false
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = false

# Short-form options
short_to_long_function_def = false
long_to_short_function_def = false

# Line joining
join_lines_based_on_source = true
